config/routes.rb
TextPlusRkim::Application.routes.draw do
  resources :show_calls do
    collection { post :import }
  end

  root :to => 'show_calls#index'

  

end

app/models/show_call.rb
class ShowCall < ActiveRecord::Base
  validates :uuid, presence: true
  validates :direction, presence: true
  # validates :direction, presence: true
	attr_accessible :uuid, 
                  :direction, 
                  :created, 
                  :created_epoch, 
                  :name, 
                  :state,
                  :cid_name,
                  :cid_num,
                  :ip_addr,
                  :dest,
                  :presence_id,
                  :presence_data,
                  :callstate,
                  :callee_name,
                  :callee_num,
                  :callee_direction,
                  :call_uuid,
                  :hostname,
                  :sent_callee_name,
                  :sent_callee_num,
                  :b_uuid,
                  :b_direction,
                  :b_created,
                  :b_created_epoch,
                  :b_name,
                  :b_state,
                  :b_cid_name,
                  :b_cid_num,
                  :b_ip_addr,
                  :b_dest,
                  :b_presence_id,
                  :b_presence_data,
                  :b_callstate,
                  :b_callee_name,
                  :b_callee_num,
                  :b_callee_direction,
                  :b_sent_callee_name,
                  :b_sent_callee_num,
                  :call_created_epoch

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |show_call|
        csv << show_call.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ShowCall.create! row.to_hash
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/show_calls_controller.rb
class ShowCallsController < ApplicationController
  def index
  	@show_calls = ShowCall.order(:uuid)
  	respond_to do |format|
  		format.html
  		format.csv { send_data @show_calls.to_csv }
  	end
  end

  def show
    @show_call = ShowCall.find(params[:id])
  end

  def destroy
    @show_call = ShowCall.find(params[:id])
    @show_call.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
    end
  end

  def import
  	ShowCall.import(params[:file])
  	redirect_to root_url, notice: "Show Calls imported."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module ShowCallHelper
end

app/helpers/show_call_helper.rb
module ShowCallHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>textPlus Assessment - Robert Kim</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/show_calls/edit.html.erb
edit.html.erb

app/views/show_calls/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container">

<h1>Listing of Show Calls</h1>


	<input type="search" class="light-table-filter" data-table="order-table" placeholder="Search input filter here">
	<br>
	<br>



<table class="order-table table" id="show_calls">
	<thead>
	<tr>
		<th>UUID</th>
		<th>Direction</th>
		<th>Date Created</th>
		<th>Created Epoch</th>
		<th>Name</th>
		<th>State</th>
		<th>CID Name</th>
		<th>CID Num</th>
		<th>IP Address</th>
	</tr>
</thead>
<tbody>
<% @show_calls.each do |show_call| %>
  <tr>
  	<td><%= link_to "#{show_call.uuid}", show_call %></td>
  	<td><%= show_call.direction %></td>
  	<td><%= show_call.created %></td>
  	<td><%= show_call.created_epoch %></td>
  	<td><%= show_call.name %></td>
  	<td><%= show_call.state %></td>
  	<td><%= show_call.cid_name %></td>
  	<td><%= show_call.cid_num %></td>
  	<td><%= show_call.ip_addr %></td>
  	<td><%= link_to 'Destroy', show_call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
</section>

<h2>Import Show Calls in CSV file format</h2>

<%= form_tag import_show_calls_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<h2>Download this listing</h2>
<p>
	Download to
	<%= link_to "CSV file format", show_calls_path(format: "csv") %>
</p>

app/views/show_calls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', show_calls_path %>

<h1>Attributes of selected show call</h1>

<table>
	<thead>
		<tr>
			<th><strong>Title</strong></th>
			<th><strong>Detail</strong></th>
   </thead>

   <tbody>
    <% @updated_attributes = @show_call.attributes.except!("id", "created_at", "updated_at") %>
    
    <% @updated_attributes.each do |k,v| %>
    <tr>
     <td><%= k %></td>
     <td><%= v %></td>
   </tr>
   <% end %>
   
   
 </tbody>
</table> 

<br>

<%= link_to 'Back', show_calls_path %>